
language: cpp
sudo: required
dist: bionic

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated libblas-dev libboost-all-dev libgfortran3 libgmp-dev liblapack-dev libopenmpi-dev libclang-dev libgsl-dev libomp-dev

install: true

script:
  - export INSTALL_DIR=$HOME/root_install # We install outside the repository
  # ===== Set up NRGLjubljana and test
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR #-DASAN=ON -DUBSAN=ON
  - export CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 && make test

