
language: cpp
sudo: required
dist: focal

compiler:
  - gcc
#  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated libblas-dev libboost-all-dev libgmp-dev liblapack-dev libopenmpi-dev libclang-dev libgsl-dev libomp-dev libhdf5-dev
#  - sudo apt-get install -y --allow-unauthenticated clang-format clang-tidy clang-tools clang clangd  libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1  liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev  llvm-runtime llvm python-clang 

install: true

script:
  - export INSTALL_DIR=$HOME/root_install # We install outside the repository
  # ===== Set up NRGLjubljana and test
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR #-DASAN=ON -DUBSAN=ON
  - export CTEST_OUTPUT_ON_FAILURE=1
  - export OMP_NUM_THREADS=1
#  - export LD_LIBRARY_PATH=/usr/lib/llvm-*/lib:$LD_LIBRARY_PATH
  - make VERBOSE=1 -j2 && make test
